" Eva Lott
" .vimrc
" vim config file

set encoding=utf-8
syntax on
filetype plugin on
filetype indent on
colorscheme customized
set autoindent
set number
set mouse=a
set clipboard=unnamedplus
set relativenumber
set cursorline
set nowrap
map <Tab> <C-W>w
set noshowmode

" swap file settigs
set nobackup
set noswapfile
set noundofile

" hotkeys
	" latex
	nnoremap <Leader>ll :!pdflatex %:p; cp *.pdf ..;
	"rm ../*.log ../*.aux;
	" ALE
	map <Leader>ld :ALEDetail

" airline settings
let g:airline_detect_whitespace=0
let g:airline_powerline_fonts = 0
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_powerline_fonts = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.whitespace = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.crypt = ''
let g:airline_symbols.columnr = ''

" ale settings
let g:ale_warn_about_trailing_whitespace = 0
let g:ale_warn_about_trailing_whitespace = 0
let g:airline#extensions#whitespace#mixed_indent_algo = 2
let g:ale_pattern_options = {
\   '.*\.tex$': {'ale_enabled': 0},
\}
